### ISSUE TITLE
Fatal error running the news module

### ISSUE THREAD

**Issue by bekaxe** [Joomla-Ukraine/JUNewsUltra#13]
Fatal error: require_once(): Failed opening required '/homepages/20/d216982147/htdocs/skiclub2015/libraries/julib/image.php' (include_path='.:/usr/lib/php7.2') in /homepages/20/d216982147/htdocs/skiclub2015/modules/mod_junewsultra/mod_junewsultra.php on line 20

JUNewsUltra Pro | Site | Modul | 6.5.10

**Comment by denysdesign** [comment]
Reinstall module puckage or install library 
https://github.com/Joomla-Ukraine/JULib
