### ISSUE TITLE
Read All News link not worked

### ISSUE THREAD

**Issue by koguja** [Joomla-Ukraine/JUNewsUltra#14]
В версии 6.5.11 перестал работать линк . вместо него подставляется само название ссылки.
В 6.5.10 вся было исправно

**Comment by denysdesign** [comment]
Какая версия Joomla?

**Comment by koguja** [comment]
3.9.5

**Comment by koguja** [comment]
Причём я пробовал линковать меню, или свой линк. Одинаково не видит.
Не получилось ли, что  упрощая в 6.5.10 mod_junewsultra.php с 158 строки у Вас  не идут данные по меню.

**Comment by denysdesign** [comment]
Исправлено!
