### ISSUE TITLE
Не работает изображение из параметров вступительного текста v6.6.0

### ISSUE THREAD

**Issue by ghost** [Joomla-Ukraine/JUNewsUltra#15]
Доброе время суток!
Joomla 3.9.12 + JUNewsUltra 6.6.0
1. После обновления модуля до версии 6.6.0 перестали работать изображение из параметров вступительного текста. В место этого выводится изображение "изображение не найдено". В версии 6.5.12 всё было прекрасно.
2. Очищает все теги во вступительном тексте, даже если переключатель "Очистить теги в тексте
" выключен. В версии 6.5.12 всё было прекрасно.

**Comment by denysdesign** [comment]
Спасибо за реакцию.
Сделаю правки и обновлю код!

**Comment by denysdesign** [comment]
Пожалуйста, обновитесь до версии 6.6.1.

**Comment by ghost** [comment]
Обновил. Изображения появились.
Огромное спасибо!
Но все теги вступительного текста очищаются не смотря на выключенный переключатель "Очистить теги в тексте".

**Comment by denysdesign** [comment]
Обновляйтесь!

**Comment by ghost** [comment]
Да, теперь всё ОТЛИЧНО v6.6.2! Спасибо!

**Comment by Viperok** [comment]
После обновления не отображает изображение из текста статьи.
