### ISSUE TITLE
Emails address in articles show the Javascript error

### ISSUE THREAD

**Issue by SactoBob** [Joomla-Ukraine/JUNewsUltra#2]
As the title says. Article displays fine when viewing it, but through JuNewsUltra email addresses are getting processed and showing the "You must have Javascript enabled" warning rather then the actual email. (Yes JS is enabled, it appears the article is piped through this module, processed, and hence the warning.

**Comment by denysdesign** [comment]
Please disable content plugin support in the module setting.

**Comment by SactoBob** [comment]
Thanks, that worked.
