### ISSUE TITLE
Возможность выбора статьи или статей для отображения

### ISSUE THREAD

**Issue by Sulpher** [Joomla-Ukraine/JUNewsUltra#21]
Иногда нужно вывести только определенные материалы в модуле, указав вручную ID статей. 

Если можно для этого выполнить SQL запрос, то стоит описать в доке как пример. т.к. запрос востребован.

**Comment by denysdesign** [comment]
Может добавить плагин для материала?

**Comment by Sulpher** [comment]
ну не всегда нужен плагин, ведь может понадобиться вывести именно модуль... 
предлагаю поле добавить  для указания id статей и опцию "брать материалы из категории или  ручное перечисление"

**Comment by Sulpher** [comment]
Упс, сорри за невнимательность: выбор статьи есть, вот он:
![Screen Shot 2020-03-28 at 22 00 41](https://user-images.githubusercontent.com/3432048/77831392-07260800-7140-11ea-8ac1-c69c64d20b85.png)

это решает сейчас задачу. пожелание: можно поле вывести, где перечислять через запятую материалы на обработку.
