### ISSUE TITLE
Не формируется webp

### ISSUE THREAD

**Issue by Sulpher** [Joomla-Ukraine/JUNewsUltra#31]
битая картинка в webp.
<img width="314" alt="Снимок экрана 2021-02-23 в 13 38 20" src="https://user-images.githubusercontent.com/3432048/108832301-6acce580-75dc-11eb-99d5-0172dbe6bc16.png">

```<source srcset="/images/img/348x199/2/a-4ccd3589.webp" type="image/webp"><a href="/URL"><img src="/images/img/348x199/7/bitvazapultik-612388b9.jpg"... >```

обрати внимание, что у jpeg картинки ЧПУ, а у webp генерация.

PHP 7.4 10, WebP Support enabled. проверка на timeweb.ru хостинге.
<img width="1383" alt="Снимок экрана 2021-02-23 в 13 40 42" src="https://user-images.githubusercontent.com/3432048/108832593-c8613200-75dc-11eb-8816-7df1fb719b1e.png">

**Comment by denysdesign** [comment]
Какой путь к imagemagick? И поддерживает ли версия imagemagick webp?

**Comment by Sulpher** [comment]
> Какой путь к imagemagick? И поддерживает ли версия imagemagick webp?

у хостера не вижу imagemagick в списке форматов. напишу им. 
а какая актуальная версия imagemagick? у хостера 3.4.3
<img width="2121" alt="Снимок экрана 2021-02-23 в 14 23 01" src="https://user-images.githubusercontent.com/3432048/108837244-02353700-75e3-11eb-9bde-03eba7a64d0e.png">

**Comment by Sulpher** [comment]
ответ хостера:
"хостинг использует совместную работу веб-серверов Nginx+Apache, где за обработку статических файлов отвечает Nginx. Внести изменения в его конфигурацию невозможно, к сожалению, т.к. на одном сервере множество клиентов."

можно ли предусмотреть обработку webp опционально через jpg?
