### ISSUE TITLE
путь img по умолчанию создает папку

### ISSUE THREAD

**Issue by Sulpher** [Joomla-Ukraine/JUNewsUltra#36]
в настройках можно указать путь к папке, в которой будут храниться миниатюры и с этим есть проблема.
когда создаешь модуль первый раз, то нужно его сохранить, чтобы открылась конфигурация. 
и после первого сохранения сразу же добавляется на сервер в корень сайта папка img.
да, можно ручками путь поправить, но придется и папку из корня удалять.
неудобно.

**Comment by denysdesign** [comment]
Этот момент решается на этапе разработки, не понравилась папка, поменял путь, протестил, оставил как нужно, а img удалил.
