### ISSUE TITLE
Picture Not Found displaying after update (was working before)

### ISSUE THREAD

**Issue by aevarez** [Joomla-Ukraine/JUNewsUltra#39]
hi hi
I am using this module on one news site and I just updated the module to the latest version today. Now suddenly all the pictures that were displaying wont display anymore, and the Picture Not Found - images displays instead. any ideas why this might be happening?

**Comment by aevarez** [comment]
Hi again.
I figured this out. The problem was in the settings. As soon as I disabled: "Display Youtube or Vimeo thumb" the original pictures from the article came up again. 
It is strange though that I don't remember messing with this ever before, unless this is a new feature with the actived set as default :Þ

**Comment by denysdesign** [comment]
Please update to JUNewsUltra Pro 6.11!

Thnx!
