### ISSUE TITLE
2 нотиса при включении maximum ошибок

### ISSUE THREAD

**Issue by Sulpher** [Joomla-Ukraine/JUNewsUltra#40]
На фронте:
шаблон default.php, вывод списком материалов без картинок:
<img width="355" alt="Снимок экрана 2021-03-08 в 23 25 27" src="https://user-images.githubusercontent.com/3432048/110377554-95e81800-8065-11eb-80e9-c355de99aeeb.png">

Notice: Undefined offset: 1 in /home/public_html/modules/mod_junewsultra/mod_junewsultra.php on line 161

В админке:
<img width="785" alt="Снимок экрана 2021-03-08 в 23 23 54" src="https://user-images.githubusercontent.com/3432048/110377414-6cc78780-8065-11eb-9bff-c931a361001b.png">

Вкладка "общее":
Notice: Undefined offset: 0 in /home//public_html/modules/mod_junewsultra/fields/multicategories.php on line 59

Junewsultra 6.10
PHP 7.4.10
J3.9

**Comment by denysdesign** [comment]
Добавил изменения в эти файлы в репу. Проверь есть ли ошибка

**Comment by Sulpher** [comment]
проверил - нотисы исчезли.
