### ISSUE TITLE
Перестали отображаться изображения к материалам

### ISSUE THREAD

**Issue by skater58** [Joomla-Ukraine/JUNewsUltra#41]
После последнего обновления до версии 6.10 пропали изображения к материалам. Загружается стандартное фото, когда отсутствует фото в материале  /img/50x50/4/notfoundimage-316fcdfb.jpg.

Заранее спасибо!

**Comment by denysdesign** [comment]
Установлен ли ImageMagick?

Если нет, отключите поддержку ImageMagick в опциях модуля

**Comment by HiopsNerevar** [comment]
Столкнулся с той же проблемой. Помогло отключение интеграции YouTube. После этого всё заработало. 
Хотя с YouTube тоже странное дело есть. Работает только с видео которые уже удалены или заблокированы. Если видео работает - изображение не делается. Если что, могу скинуть сайт.
И сразу тут спрошу чтобы не плодить темы. Есть ли надежда на интеграцию с CComment? JComments уже умирает, Komento стал платным. А у CComment есть бесплатная версия и компонент явно набирает обороты. Был бы рад видеть поддержку в вашем модуле! Спасибо!

**Comment by denysdesign** [comment]
Словил ошибку.
Подправлю.

**Comment by denysdesign** [comment]
Пожалуйста, обновитесь на версию JUNewsUltra Pro 6.11
Данные ошибки были исправлены!

Пожалуйста, отпишитесь в любом случае, даже если все хорошо работает!

Спасибо!

**Comment by skater58** [comment]
Обновился и снова та же проблема ((

**Comment by denysdesign** [comment]
Попробуйте удалить папку /img

**Comment by skater58** [comment]
Удаление папки /img не решило проблему. Только откат на более позднюю версию ...

**Comment by ugamer123** [comment]
Такая же проблема joomla 3.9.25
junewsultra 6.11pro
PHP Version 7.2.24
Не показывается изображение, конктерно : http://joxi.ru/l2ZQ8e9FRLpPjm
пробовал так: http://joxi.ru/J2baE3WSg5d6gm тоже не работает


Откатился до 6.9 полет нормальный, на 6.10 и выше уже не пашет. Пожалуйста пофиксите.
