### ISSUE TITLE
Помилка при встановленні JUNewsUltra 4.7 на Joomla 4.2.7

### ISSUE THREAD

**Issue by ladoleo** [Joomla-Ukraine/JUNewsUltra#47]
Too few arguments to function Pkg_JUNewsUltraInstallerScript::postflight(), 2 passed and exactly 3 expected 

Отримую ось це під час встановлення. PHP 8.1

**Comment by denysdesign** [comment]
Будь ласка, оновіть модуль до версії JUNewsUltra Pro 7.5

**Comment by ladoleo** [comment]
Дякую за таке швидке реагування. :)
Я взагалі то вручну усе встановив і наче все добре.

ср, 8 лют. 2023 р., 13:35 користувач Denys Nosov ***@***.***>
пише:

**Comment by denysdesign** [comment]
Якщо що, то пишіть 👍

**Comment by ladoleo** [comment]
Без питань. Дякую!!!

ср, 8 лют. 2023 р., 13:56 користувач Denys Nosov ***@***.***>
пише:

**Comment by ladoleo** [comment]
Доброго дня іще раз. Тут з плагіном
*JUMultiThumb <https://github.com/Joomla-Ukraine/JUMultiThumb> проблема ось
така:*
Call to undefined method
Joomla\CMS\Document\HtmlDocument::addScriptVersion()

ср, 8 февр. 2023 г. в 13:57, Leo Lado ***@***.***>:

**Comment by denysdesign** [comment]
Наразі ведеться робота по адаптації плагіну

**Comment by ladoleo** [comment]
Зрозумів. Дякую.

ср, 8 лют. 2023 р., 14:47 користувач Denys Nosov ***@***.***>
пише:
